- name: Restart System
  panos_restart:
    provider: "{{ provider }}"

- name: wait for reboot
  panos_check:
    provider: "{{ provider }}"
    initial_delay: 120
    interval: 15
    timeout: 600
  register: check

- debug:
    var: check