- name: Generate Tech Support File
  panos_op:
    provider:
      api_key: "{{ auth.api_key }}"
      ip_address: "{{ ip_address }}"
    cmd: "scp export tech-support to {{ scp_user }}@{{ scp_hostname }}:{{ path }}"