- name: Restart Process
  panos_op:
    provider:
      api_key: "{{ auth.api_key }}"
      ip_address: "{{ ip_address }}"
    cmd: "debug software restart process {{ software }} core yes"

- name: wait for reboot
  panos_check:
    provider:
      api_key: "{{ auth.api_key }}"
      ip_address: "{{ ip_address }}"
    initial_delay: 120
    interval: 5
    timeout: 600