---
- name: "Scenario 1 : Create new group policy in case already has group IP"
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: address_group_name
      prompt: Enter Address Group Name
      private: no
    - name: address_name
      prompt: Enter Address Name
      private: no
    - name: rule_name
      prompt: Enter rule name
      private: no
    - name: source_ip
      prompt: Enter source IP
      private: no
      default: "any"
    - name: destination_ip
      prompt: Enter destination IP
      private: no
      default: "any"
    - name: service
      prompt: Enter service
      private: no
      default: "application-default"
  vars:
    action: allow
  collections:
  - paloaltonetworks.panos 
  roles:
  - PaloAltoNetworks.paloaltonetworks
  - api_key
  - add_address_group
  - add_security_rule_with_have_rule
  - commit
  