---
- name: "Scenario 3 : Add only IP into existing policy"
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: rule_name
      prompt: Enter rule name
      private: no
    - name: source_ip
      prompt: Enter source IP
      private: no
    - name: destination_ip
      prompt: Enter destination IP
      private: no
    - name: service
      prompt: Enter service
      private: no
  vars:
    action: allow
  collections:
  - paloaltonetworks.panos 
  roles:
  - PaloAltoNetworks.paloaltonetworks
  - api_key
  - add_security_rule_with_have_rule
  - commit
  