---
- name: Check Palo Alto ready config
  hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: initial_delay
    prompt: Enter initial_delay
    private: no
    default: 120
  - name: interval
    prompt: Enter interval time
    private: no
    default: 5
  - name: timeout
    prompt: Enter timeout
    private: no
    default: 600
  collections:
  - paloaltonetworks.panos
  roles:
    - PaloAltoNetworks.paloaltonetworks
    - api_key
    - check