---
- name: Generate Tech Support
  hosts: localhost
  gather_facts: no
  collections:
  - paloaltonetworks.panos
  # roles:
  #   - api_key
  #   - generate_tech_support

  tasks:
    - name: get api key
      panos_api_key: 
        provider: 
            ip_address: "{{ ip_address }}"
            username: "{{ username }}"
            password: "{{ password }}"
      register: auth

    - name: Generate Tech Support File
      panos_op:
        provider:
          ip_address: "{{ ip_address }}"
          api_key: "{{ auth.api_key }}"
        cmd: "request tech-support dump"
