---
- name: Generate Tech Support
  hosts: localhost
  gather_facts: no
  vars_prompt:
  collections:
  - paloaltonetworks.panos
  roles:
    - PaloAltoNetworks.paloaltonetworks
    - api_key
    - generate_tech_support
