---
- name: Generate Tech Support
  hosts: localhost
  gather_facts: no
  collections:
  - paloaltonetworks.panos
  # roles:
  #   - api_key
  #   - generate_tech_support

  tasks:
    - name: get api key
      panos_api_key:
        provider:
            ip_address: "{{ ip_address }}"
            username: "{{ username }}"
            password: "{{ password }}"
      register: auth

    - name: Create a job to retrieve technical support data
      uri:
        url: "https://{{ ip_address }}/api/?key={{ auth.api_key }}&type=export&category=tech-support"
        return_content: yes
        validate_certs: no
      register: job_id
    
    - set_fact:
        output: "{{  job_id.content.split().7}}"
 
    - set_fact:
        id: "{{ output.split('<').0 }}"

    # Pause for 2 minutes to create tech-support
    - pause:
        minutes: "{{ pause_time | default( 2 ) }}"

    - name: Check on the status of the job
      uri:
        url: "https://{{ ip_address }}/api/?key={{ auth.api_key }}&type=export&category=tech-support&action=status&job-id={{ id }}"
        return_content: yes
        validate_certs: no
      register: job_status

    - set_fact:
        date_time1: "{{ job_status.content.split('<tenq>').1 }}"
 
    - set_fact:
        date_time2: "{{ date_time1.split('</tenq>').0 }}"

    - set_fact:
        date_not_fillter: "{{ date_time2.split().0 }}"
        time_not_fillter: "{{ date_time2.split().1 }}"

    - set_fact:
        date: "{{ date_not_fillter.split('/') | join('') }}"
        time: "{{ time_not_fillter.split(':') | join('') }}"

    - set_fact:
        file_name: "{{ date }}_{{ time }}_techsupport.tgz"

    - name: Retrieve the tech support data.
      shell: "curl https://{{ ip_address }}/api/?key={{ auth.api_key }}&type=export&category=tech-support&action=status&job-id={{ id }} -o -s {{ file_path }}/{{ file_name }}"
      delegate_to: localhost
      when: >
        'OK' in job_status.msg and 
        job_status.status == '200'

    # - name: Generate Tech Support File
    #   panos_op:
    #     provider:
    #       ip_address: "{{ ip_address }}"
    #       api_key: "{{ auth.api_key }}"
    #     cmd: <request><tech-support><dump></dump></tech-support></request>
    #     cmd_is_xml: yes
