---
  - name: paloaltonetworks.panos
    version: 1.1.0
    src: https://galaxy.ansible.com/paloaltonetworks/panos

  - name: paloaltonetworks.paloaltonetworks
    version: 2.4.1
    src: https://galaxy.ansible.com/paloaltonetworks/paloaltonetworks
