---
- name: Restart Process
  hosts: localhost
  gather_facts: no
  connection: local
  vars_prompt:
  - name: ip_address
    prompt: Enter Palo Alto IP
    private: no
  - name: username
    prompt: Enter Palo Alto Username
    private: no
  - name: password
    prompt: Enter Palo Alto Password
    private: no
  roles:
    - PaloAltoNetworks.paloaltonetworks
    - api_key
    - restart_process

# extra var: software, ip_address, username, password