---
- name: Show Cluster Status
  hosts: localhost
  gather_facts: no
  collections:
  - paloaltonetworks.panos

  tasks:
  - name: get api key
    panos_api_key: 
      provider: 
        ip_address: "{{ ip_address }}"
        username: "{{ username }}"
        password: "{{ password }}"
    register: auth

  roles:
    # - api_key
    - high_availability_state
    - fail_over