---
- name: Show Cluster Status
  hosts: localhost
  gather_facts: no
  collections:
  - paloaltonetworks.panos

  roles:
    - PaloAltoNetworks.paloaltonetworks
    # - api_key
    - high_availability_state
    - fail_over