---
- name: Show Cluster Status
  hosts: localhost
  gather_facts: no
  collections:
  - paloaltonetworks.panos

  roles:
    # - api_key
    # - high_availability_state
    # - fail_over

  tasks:
    - name: get api key
      panos_op: 
        provider: 
            ip_address: "{{ ip_address }}"
            username: "{{ username }}"
            password: "{{ password }}"
      register: auth