---
- name: Restart Palo Alto System
  hosts: localhost
  gather_facts: no
  # vars_prompt:
  # - name: ip_address
  #   prompt: Enter Palo Alto IP
  #   private: no
  # - name: username
  #   prompt: Enter Palo Alto Username
  #   private: no
  # - name: password
  #   prompt: Enter Palo Alto Password
  #   private: no
  collections:
  - paloaltonetworks.panos
  # roles:
  #   - PaloAltoNetworks.paloaltonetworks
  #   - api_key
  #   - system_restart

  tasks:
    - name: get api key
      panos_api_key: 
        provider: 
            ip_address: "{{ ip_address }}"
            username: "{{ username }}"
            password: "{{ password }}"
      register: auth

    - name: Restart System
      panos_restart:
        provider:
          ip_address: "{{ ip_address }}"
          api_key: "{{ auth.api_key }}"

    - name: wait for reboot
      panos_check:
        provider:
          ip_address: "{{ ip_address }}"
          api_key: "{{ auth.api_key }}"
        initial_delay: 60
        interval: 0
        timeout: 86400
      register: check

    - debug:
        var: check