---
- name: Restart Palo Alto System
  hosts: localhost
  gather_facts: no
  vars_prompt:
  collections:
  - paloaltonetworks.panos
  roles:
    - PaloAltoNetworks.paloaltonetworks
    - api_key
    - system_restart