---
- name: Restart Palo Alto System
  hosts: localhost
  gather_facts: no
  collections:
  - paloaltonetworks.panos

  tasks:
    - name: get api key
      panos_api_key: 
        provider: 
            ip_address: "{{ ip_address }}"
            username: "{{ username }}"
            password: "{{ password }}"
      register: auth

    - name: Get facts
      panos_facts:
        provider:
          ip_address: "{{ ip_address }}"
          api_key: "{{ auth.api_key }}"
        gather_subset: ['system']
      register: uptime_before_restart

    - debug:
        msg: "{{ uptime_before_restart }}"

    - name: Restart System
      panos_restart:
        provider:
          ip_address: "{{ ip_address }}"
          api_key: "{{ auth.api_key }}"

    - name: wait for reboot
      panos_check:
        provider:
          ip_address: "{{ ip_address }}"
          api_key: "{{ auth.api_key }}"
        initial_delay: 60
        interval: 0
        timeout: 86400
      register: check

    - debug:
        var: check

    - name: Get facts
      panos_facts:
        provider:
          ip_address: "{{ ip_address }}"
          api_key: "{{ auth.api_key }}"
        gather_subset: ['system']
      register: uptime_after_restart

    - debug:
        msg: "{{ uptime_after_restart }}"