  - name: Create object 'Test-One'
    panos_address_object:
      provider:
        api_key: "{{ auth.api_key }}"
        ip_address: "{{ ip_address }}"
      name: "{{ block_ip }}"
      value: "{{ ip_mask }}"

  - name: Add IP Block-list Object group
    panos_address_group:
      provider:
        api_key: "{{ auth.api_key }}"
        ip_address: "{{ ip_address }}"
      name: "{{ block_group }}"
      static_value: "{{ block_ip }}"

  - name: Install Policy
    panos_commit:
      provider:
        api_key: "{{ auth.api_key }}"
        ip_address: "{{ ip_address }}"
