- name: import set facts
  import_tasks: check_fact.yml

- name: Create Policy and add Address or Address Group into policy
  panos_security_rule:
    provider: "{{ provider }}"
    device_group: "{{ device_group | default('shared')}}"
    rule_name: "{{ rule_name }}"
    source_zone: ["{{ source_zone | default('any') }}"]
    source_ip: "{{ source_ip  }}"
    destination_zone: ["{{ destination_zone | default('any') }}"]
    destination_ip: "{{ destination_ip  }}"
    application: ["{{ application | default('any') }}"]
    action: "{{ action }}"
    service: "{{ service }}"